version: '3.8'

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: grades
      MYSQL_DATABASE: grades
      MYSQL_USER: grades
      MYSQL_PASSWORD: grades
      TZ: Asia/Shanghai
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./backend/db/init:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"

  backend:
    build: backend/app
    container_name: grades_backend_app
    restart: always
    environment:
      TZ: Asia/Shanghai
      DB_HOST: db
      DB_USER: grades
      DB_PASSWORD: grades
      DB_DATABASE: grades

  proxy:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/static
      - ./nginx/cert:/cert
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8080:80"


volumes:
  mariadb_data:

