name: Redeploy

on:
  push:
    branches:
      - 'main'

jobs:
  redeploy:
    name: Redeploy webhook call
    runs-on: ubuntu-18.04
    needs: [docker]
    steps:
      - name: Deploy docker compose webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: "http://groupwork.xiran.xyz:9000/hooks/75c04a03-a33a-4468-a44a-4f406cd5ca78"